# Generated by Django 3.0.6 on 2020-06-13 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='photo',
            new_name='image',
        ),
    ]
