# Generated by Django 3.0.6 on 2020-06-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200613_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles')),
                ('bio', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
